build:
  image: golang:1.4.3
  commands:
    - go version 
    - go build
    - go test go2xunit_test.go -v

deploy:
  rsync:
    user: root
    host: 172.17.0.1
    port: 22
    source: go2xunit
    target: /disk1/downloads/